name: CI
on:
  push:
    branches:
      - "master"
      - release-*
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            name: Windows
#          - os: ubuntu-20.04
#            name: Linux
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 7.0.x
      - name: Build exercise 01 - before
        run: dotnet build exercises/01-composite-ui/before --configuration Release
      - name: Build exercise 01 - after
        run: dotnet build exercises/01-composite-ui/after --configuration Release
      - name: Build exercise 02 - before
        run: dotnet build exercises/02-publish-subscribe/before --configuration Release
      - name: Build exercise 02 - after
        run: dotnet build exercises/02-publish-subscribe/after --configuration Release
      - name: Build exercise 03 - before
        run: dotnet build exercises/03-sagas/before --configuration Release
      - name: Build exercise 03 - after
        run: dotnet build exercises/03-sagas/after --configuration Release
      - name: Build exercise 04 - before
        run: dotnet build exercises/04-integration/before --configuration Release
      - name: Build exercise 04 - after
        run: dotnet build exercises/04-integration/after --configuration Release
#      - name: CompositeUI demo
#        run: dotnet build demos/asp-net-core/Divergent.Website.sln --configuration Release
